### ISSUE TITLE
Unsound usages of unsafe implementation from `[u8]` to `Json`

### ISSUE THREAD

**Issue by llooFlashooll** [apoelstra/strason#4]
Hi, I am scanning the strason in the latest version with my own static analyzer tool.

Unsafe conversion found at: src/object.rs#L40
``` rust
   fn visit_bytes<E: de::Error>(self, buf: &[u8]) -> Result<Json, E> {
         unsafe {
            let ptr = buf.as_ptr() as *const Json;
            Ok((*ptr).clone())
         }
   }
```

This unsound implementation would create a misalignment issues if the type size of `[u8]` is smaller than the type size of `Json`.

This would potentially cause [undefined behaviors](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) in Rust. If we further manipulate the problematic converted types, it would potentially lead to different consequences such as access out-of-bound. I am reporting this issue for your attention.

**Comment by apoelstra** [comment]
Thanks for the heads up. This library has been unmaintained for the last 6+ years and abandoned because of its use of unsound code (among other reasons).

I will leave this bug open until I update the README to reflect this, and maybe push a new major rev that deletes the library so that people who access it through crates.io will be discouraged from using it.

But meanwhile you can save your energy for scanning other crates.
